apiVersion: v1
kind: Service
metadata:
  name: myapp-service

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80 #zorunlu kısım burası
      nodePort: 30008
  selector:
    app: myapp
    type: front-end

---

apiVersion: v1
kind: Service
metadata:
  name: back-end-service

spec:
  type: ClusterIP #default'tur vermesek de olur.
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: myapp
    type: back-end

# Target port tanımlamazsak bunun port ile aynı olduğunu varsayılır.