apiVersion: v1
kind: Pod
metadata:
  name: simple
  labels:
    name: simple
spec:
  containers:
    - name: simple
      image: simple
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "4Gi"
          cpu: 2
        limits:
          memory: "2Gi"
          cpu: 2