apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: simple-webapp
      image: simple-webapp

  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"

#node'a eklenen taintlerin aynısı eklenir.

